input_columns = [ "gender", "seniorcitizen", "partner", "dependents", "tenure", "phoneservice", "multiplelines", "internetservice", "onlinesecurity", "onlinebackup", "deviceprotection", "techsupport", "streamingtv", "streamingmovies", "contract", "paperlessbilling", "paymentmethod", "monthlycharges", "totalcharges",]
two_value_categorial_columns = [ "gender", "seniorcitizen", "partner", "dependents", "phoneservice", "paperlessbilling",]
more_value_categorial_columns = [ "multiplelines", "internetservice", "onlinesecurity", "onlinebackup", "deviceprotection", "techsupport", "streamingtv", "streamingmovies", "contract", "paymentmethod",]
numerical_columns = [ "tenure", "monthlycharges", "totalcharges",]

[categories_with_values]
gender = [ "female", "male",]
seniorcitizen = [ "no", "yes",]
partner = [ "yes", "no",]
dependents = [ "no", "yes",]
phoneservice = [ "no", "yes",]
multiplelines = [ "no phone service", "no", "yes",]
internetservice = [ "dsl", "fiber optic", "no",]
onlinesecurity = [ "no", "yes", "no internet service",]
onlinebackup = [ "yes", "no", "no internet service",]
deviceprotection = [ "no", "yes", "no internet service",]
techsupport = [ "no", "yes", "no internet service",]
streamingtv = [ "no", "yes", "no internet service",]
streamingmovies = [ "no", "yes", "no internet service",]
contract = [ "month-to-month", "one year", "two year",]
paperlessbilling = [ "yes", "no",]
paymentmethod = [ "electronic check", "mailed check", "bank transfer (automatic)", "credit card (automatic)",]
